slider_controller_pos:
  type: effort_controllers/JointGroupPositionController
  joints: 
    - slider1_control
    - slider2_control
  
  slider1_control:
    pid: {p: 10.0, i: 1.0, d: 1.0}
  slider2_control:
    pid: {p: 25.0, i: 2.5, d: 5.0}